### ISSUE TITLE
Symfony 4.3 Depreciated Usage of EventDispatcher::dispatch()

### ISSUE THREAD

**Issue by fyrye** [shapecode/twig-template-event-bundle#1]
**Version(s) affected**: 3.1.*

**Description**  
Current usage of `Shapecode\Bundle\TwigTemplateEventBundle\Services\EventService::handleEvent()` method causes 3 depreciation notices to be emitted.

Notice:

<blockquote>
Calling the "Symfony\Component\EventDispatcher\EventDispatcherInterface::dispatch()" method with the event name as the first argument is deprecated since Symfony 4.3, pass it as the second argument and provide the event object as the first argument instead.
</blockquote>

**How to reproduce**  
N/A

**Possible Solution**  
Add conditional to check version constraints of the Kernel to switch argument placement of `EventDispatcher::dispatch()`

**Comment by nicklog** [comment]
Hey, thank you for your PR. I will check it by time.

Greetings.

**Comment by fyrye** [comment]
@nicklog Wow massive update, thanks!
I'll check it out in my dev environment and see if there are any issues.

**Comment by fyrye** [comment]
@nicklog ran into an issue with Symfony 4.4 and 5.1, where Symfony only requires `php >=7.1.3` and Symfony 5 requires `php >=7.2.5`  Personally I am currently stuck on php 7.2 due to a backward incompatible change in 7.3

Unless there are specific reasons to require `php ~7.3` , would you consider matching Symfony at `php >= 7.2.5`?

**Comment by fyrye** [comment]
@nicklog all is working well in my tests in both php 7.2 and 7.3. 

As there are no PHP 7.3 specific features in your package, my only suggestion would be to reduce the platform requirements to match that of [Symfony 5.1](https://github.com/symfony/symfony/blob/5.1/composer.json#L19) to `"php": ">=7.2.5"` to reach a wider audience and align better with the Symfony platform requirements.

**Comment by nicklog** [comment]
Yes, we can do that :) 
https://github.com/shapecode/twig-template-event-bundle/runs/950448226
